package tech.thatgravyboat.skyblockapi.api.area.farming.garden

enum class FarmingTool() {
    THEORETICAL_HOE_WHEAT,
    THEORETICAL_HOE_CARROT,
    THEORETICAL_HOE_POTATO,
    PUMPKIN_DICER,
    THEORETICAL_HOE_CANE,
    MELON_DICER,
    CACTUS_KNIFE,
    COCO_CHOPPER,
    FUNGI_CUTTER,
    THEORETICAL_HOE_WARTS,
    THEORETICAL_HOE_SUNFLOWER,
    THEORETICAL_HOE_WILD_ROSE,
}
