[versions]
minecraft-start = "26.1-alpha.11"
minecraft-end = "26.1"
minecraft = "26.1-snapshot-11"

sbapi-mc-version = "1.21.11"
fabric-api = "0.143.10+26.1"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }

fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api" }
