[versions]
minecraft-range = "26.1.x"
minecraft = "26.1-rc-1"

sbapi-mc-version = "26.1"
fabric-api = "0.143.12+26.1"

hypixel-modapi = "1.0.1"
hypixel-modapi-fabric = "1.0.1+build.dev+mc26.1-pre-1-custom.26.1-port.build+2"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }

fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api" }

hypixel-modapi = { module = "net.hypixel:mod-api", version.ref = "hypixel-modapi" }
#todo change back to maven.modrinth once hypixel updates
hypixel-modapi-fabric = { module = "net.hypixel:FabricModAPI", version.ref = "hypixel-modapi-fabric" }

#https://maven.teamresourceful.com/repository/maven-public/net/hypixel/FabricModAPI/1.0.1+build.dev+mc26.1-pre-1-custom.26.1-port/FabricModAPI-1.0.1+build.dev+mc26.1-pre-1-custom.26.1-port.pom
[bundles]
hypixel = ["hypixel-modapi", "hypixel-modapi-fabric"]
