[versions]
minecraft-range = "26.3.x"
minecraft = "26.3-snapshot-10"

sbapi-mc-version = "26.3"
fabric-api = "0.158.2+26.3"

hypixel-modapi = "1.0.2"
hypixel-modapi-fabric = "1.0.2+build.1+mc26.1"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }

fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api" }

hypixel-modapi = { module = "net.hypixel:mod-api", version.ref = "hypixel-modapi" }
hypixel-modapi-fabric = { module = "maven.modrinth:hypixel-mod-api", version.ref = "hypixel-modapi-fabric" }

[bundles]
hypixel = ["hypixel-modapi", "hypixel-modapi-fabric"]
