[versions]
google-gson = "2.12.1"

meowdding-modules = "1.0.5"
meowdding-ktcodecs = "1.1.14"
meowdding-resources = "1.0.17"
meowdding-item-dfu = "1.0.12"
meowdding-auto-mixins = "1.0.8"

fabric-loader = "0.19.2"
fabric-language-kotlin = "1.13.8+kotlin.2.3.0"

kotlin = "2.3.0"
kotlin-gradle-plugin = "2.3.0"
kotlin-symbol-processor = "2.3.5"
kotlin-binary-compatibility-validator = "0.18.1"

hypixel-modapi = "1.0.2"
hypixel-modapi-fabric = "1.0.2+build.1+mc26.1"

skyblockapi-repolib = "4.1.4"

# Dev versions
devauth-fabric = "1.2.2"

[libraries]
google-gson = { module = "com.google.code.gson:gson", version.ref = "google-gson" }

meowdding-modules = { module = "me.owdding.ktmodules:KtModules", version.ref = "meowdding-modules" }
meowdding-ktcodecs = { module = "me.owdding.ktcodecs:KtCodecs", version.ref = "meowdding-ktcodecs" }
meowdding-item-dfu = { module = "me.owdding:item-data-fixer", version.ref = "meowdding-item-dfu" }

fabric-language-kotlin = { module = "net.fabricmc:fabric-language-kotlin", version.ref = "fabric-language-kotlin" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }

kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin-gradle-plugin" }
kotlin-gradle-plugin-api = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin-api", version.ref = "kotlin-gradle-plugin" }

hypixel-modapi = { module = "net.hypixel:mod-api", version.ref = "hypixel-modapi" }
hypixel-modapi-fabric = { module = "maven.modrinth:hypixel-mod-api", version.ref = "hypixel-modapi-fabric" }

skyblockapi-repolib = { module = "tech.thatgravyboat.repo-lib:repo-lib", version.ref = "skyblockapi-repolib" }
devauth = { module = "me.djtheredstoner:DevAuth-fabric", version.ref = "devauth-fabric" }

[bundles]
meowdding = ["meowdding-ktcodecs", "meowdding-modules"]
hypixel = ["hypixel-modapi", "hypixel-modapi-fabric"]

kotlin-gradle-plugin = ["kotlin-gradle-plugin", "kotlin-gradle-plugin-api"]

[plugins]

meowdding-resources = { id = "me.owdding.resources", version.ref = "meowdding-resources" }
meowdding-auto-mixins = { id = "me.owdding.auto-mixins", version.ref = "meowdding-auto-mixins" }

kotlin-binary-compatibility-validator = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version.ref = "kotlin-binary-compatibility-validator" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm" }
kotlin-symbol-processor = { id = "com.google.devtools.ksp", version.ref = "kotlin-symbol-processor" }
