package tech.thatgravyboat.skyblockapi.impl

import net.minecraft.world.level.block.Block
import net.minecraft.world.level.block.Blocks

@Suppress("unused")
@Deprecated("With 26.1 dropped soon this will become useless, will be removed with 26.4")
public object ColoredBlocks {
    //? >= 26.2 {
    public val WHITE_WOOL: Block = Blocks.WOOL.white
    public val ORANGE_WOOL: Block = Blocks.WOOL.orange
    public val MAGENTA_WOOL: Block = Blocks.WOOL.magenta
    public val LIGHT_BLUE_WOOL: Block = Blocks.WOOL.lightBlue
    public val YELLOW_WOOL: Block = Blocks.WOOL.yellow
    public val LIME_WOOL: Block = Blocks.WOOL.lime
    public val PINK_WOOL: Block = Blocks.WOOL.pink
    public val GRAY_WOOL: Block = Blocks.WOOL.gray
    public val LIGHT_GRAY_WOOL: Block = Blocks.WOOL.lightGray
    public val CYAN_WOOL: Block = Blocks.WOOL.cyan
    public val PURPLE_WOOL: Block = Blocks.WOOL.purple
    public val BLUE_WOOL: Block = Blocks.WOOL.blue
    public val BROWN_WOOL: Block = Blocks.WOOL.brown
    public val GREEN_WOOL: Block = Blocks.WOOL.green
    public val RED_WOOL: Block = Blocks.WOOL.red
    public val BLACK_WOOL: Block = Blocks.WOOL.black

    public val WHITE_STAINED_GLASS: Block = Blocks.STAINED_GLASS.white
    public val ORANGE_STAINED_GLASS: Block = Blocks.STAINED_GLASS.orange
    public val MAGENTA_STAINED_GLASS: Block = Blocks.STAINED_GLASS.magenta
    public val LIGHT_BLUE_STAINED_GLASS: Block = Blocks.STAINED_GLASS.lightBlue
    public val YELLOW_STAINED_GLASS: Block = Blocks.STAINED_GLASS.yellow
    public val LIME_STAINED_GLASS: Block = Blocks.STAINED_GLASS.lime
    public val PINK_STAINED_GLASS: Block = Blocks.STAINED_GLASS.pink
    public val GRAY_STAINED_GLASS: Block = Blocks.STAINED_GLASS.gray
    public val LIGHT_GRAY_STAINED_GLASS: Block = Blocks.STAINED_GLASS.lightGray
    public val CYAN_STAINED_GLASS: Block = Blocks.STAINED_GLASS.cyan
    public val PURPLE_STAINED_GLASS: Block = Blocks.STAINED_GLASS.purple
    public val BLUE_STAINED_GLASS: Block = Blocks.STAINED_GLASS.blue
    public val BROWN_STAINED_GLASS: Block = Blocks.STAINED_GLASS.brown
    public val GREEN_STAINED_GLASS: Block = Blocks.STAINED_GLASS.green
    public val RED_STAINED_GLASS: Block = Blocks.STAINED_GLASS.red
    public val BLACK_STAINED_GLASS: Block = Blocks.STAINED_GLASS.black

    public val WHITE_TERRACOTTA: Block = Blocks.DYED_TERRACOTTA.white
    public val ORANGE_TERRACOTTA: Block = Blocks.DYED_TERRACOTTA.orange
    public val MAGENTA_TERRACOTTA: Block = Blocks.DYED_TERRACOTTA.magenta
    public val LIGHT_BLUE_TERRACOTTA: Block = Blocks.DYED_TERRACOTTA.lightBlue
    public val YELLOW_TERRACOTTA: Block = Blocks.DYED_TERRACOTTA.yellow
    public val LIME_TERRACOTTA: Block = Blocks.DYED_TERRACOTTA.lime
    public val PINK_TERRACOTTA: Block = Blocks.DYED_TERRACOTTA.pink
    public val GRAY_TERRACOTTA: Block = Blocks.DYED_TERRACOTTA.gray
    public val LIGHT_GRAY_TERRACOTTA: Block = Blocks.DYED_TERRACOTTA.lightGray
    public val CYAN_TERRACOTTA: Block = Blocks.DYED_TERRACOTTA.cyan
    public val PURPLE_TERRACOTTA: Block = Blocks.DYED_TERRACOTTA.purple
    public val BLUE_TERRACOTTA: Block = Blocks.DYED_TERRACOTTA.blue
    public val BROWN_TERRACOTTA: Block = Blocks.DYED_TERRACOTTA.brown
    public val GREEN_TERRACOTTA: Block = Blocks.DYED_TERRACOTTA.green
    public val RED_TERRACOTTA: Block = Blocks.DYED_TERRACOTTA.red
    public val BLACK_TERRACOTTA: Block = Blocks.DYED_TERRACOTTA.black

    public val WHITE_STAINED_GLASS_PANE: Block = Blocks.STAINED_GLASS_PANE.white
    public val ORANGE_STAINED_GLASS_PANE: Block = Blocks.STAINED_GLASS_PANE.orange
    public val MAGENTA_STAINED_GLASS_PANE: Block = Blocks.STAINED_GLASS_PANE.magenta
    public val LIGHT_BLUE_STAINED_GLASS_PANE: Block = Blocks.STAINED_GLASS_PANE.lightBlue
    public val YELLOW_STAINED_GLASS_PANE: Block = Blocks.STAINED_GLASS_PANE.yellow
    public val LIME_STAINED_GLASS_PANE: Block = Blocks.STAINED_GLASS_PANE.lime
    public val PINK_STAINED_GLASS_PANE: Block = Blocks.STAINED_GLASS_PANE.pink
    public val GRAY_STAINED_GLASS_PANE: Block = Blocks.STAINED_GLASS_PANE.gray
    public val LIGHT_GRAY_STAINED_GLASS_PANE: Block = Blocks.STAINED_GLASS_PANE.lightGray
    public val CYAN_STAINED_GLASS_PANE: Block = Blocks.STAINED_GLASS_PANE.cyan
    public val PURPLE_STAINED_GLASS_PANE: Block = Blocks.STAINED_GLASS_PANE.purple
    public val BLUE_STAINED_GLASS_PANE: Block = Blocks.STAINED_GLASS_PANE.blue
    public val BROWN_STAINED_GLASS_PANE: Block = Blocks.STAINED_GLASS_PANE.brown
    public val GREEN_STAINED_GLASS_PANE: Block = Blocks.STAINED_GLASS_PANE.green
    public val RED_STAINED_GLASS_PANE: Block = Blocks.STAINED_GLASS_PANE.red
    public val BLACK_STAINED_GLASS_PANE: Block = Blocks.STAINED_GLASS_PANE.black

    public val WHITE_CARPET: Block = Blocks.CARPET.white
    public val ORANGE_CARPET: Block = Blocks.CARPET.orange
    public val MAGENTA_CARPET: Block = Blocks.CARPET.magenta
    public val LIGHT_BLUE_CARPET: Block = Blocks.CARPET.lightBlue
    public val YELLOW_CARPET: Block = Blocks.CARPET.yellow
    public val LIME_CARPET: Block = Blocks.CARPET.lime
    public val PINK_CARPET: Block = Blocks.CARPET.pink
    public val GRAY_CARPET: Block = Blocks.CARPET.gray
    public val LIGHT_GRAY_CARPET: Block = Blocks.CARPET.lightGray
    public val CYAN_CARPET: Block = Blocks.CARPET.cyan
    public val PURPLE_CARPET: Block = Blocks.CARPET.purple
    public val BLUE_CARPET: Block = Blocks.CARPET.blue
    public val BROWN_CARPET: Block = Blocks.CARPET.brown
    public val GREEN_CARPET: Block = Blocks.CARPET.green
    public val RED_CARPET: Block = Blocks.CARPET.red
    public val BLACK_CARPET: Block = Blocks.CARPET.black

    public val WHITE_BED: Block = Blocks.BED.white
    public val ORANGE_BED: Block = Blocks.BED.orange
    public val MAGENTA_BED: Block = Blocks.BED.magenta
    public val LIGHT_BLUE_BED: Block = Blocks.BED.lightBlue
    public val YELLOW_BED: Block = Blocks.BED.yellow
    public val LIME_BED: Block = Blocks.BED.lime
    public val PINK_BED: Block = Blocks.BED.pink
    public val GRAY_BED: Block = Blocks.BED.gray
    public val LIGHT_GRAY_BED: Block = Blocks.BED.lightGray
    public val CYAN_BED: Block = Blocks.BED.cyan
    public val PURPLE_BED: Block = Blocks.BED.purple
    public val BLUE_BED: Block = Blocks.BED.blue
    public val BROWN_BED: Block = Blocks.BED.brown
    public val GREEN_BED: Block = Blocks.BED.green
    public val RED_BED: Block = Blocks.BED.red
    public val BLACK_BED: Block = Blocks.BED.black

    public val WHITE_BANNER: Block = Blocks.BANNER.white
    public val ORANGE_BANNER: Block = Blocks.BANNER.orange
    public val MAGENTA_BANNER: Block = Blocks.BANNER.magenta
    public val LIGHT_BLUE_BANNER: Block = Blocks.BANNER.lightBlue
    public val YELLOW_BANNER: Block = Blocks.BANNER.yellow
    public val LIME_BANNER: Block = Blocks.BANNER.lime
    public val PINK_BANNER: Block = Blocks.BANNER.pink
    public val GRAY_BANNER: Block = Blocks.BANNER.gray
    public val LIGHT_GRAY_BANNER: Block = Blocks.BANNER.lightGray
    public val CYAN_BANNER: Block = Blocks.BANNER.cyan
    public val PURPLE_BANNER: Block = Blocks.BANNER.purple
    public val BLUE_BANNER: Block = Blocks.BANNER.blue
    public val BROWN_BANNER: Block = Blocks.BANNER.brown
    public val GREEN_BANNER: Block = Blocks.BANNER.green
    public val RED_BANNER: Block = Blocks.BANNER.red
    public val BLACK_BANNER: Block = Blocks.BANNER.black

    public val WHITE_SHULKER_BOX: Block = Blocks.DYED_SHULKER_BOX.white
    public val ORANGE_SHULKER_BOX: Block = Blocks.DYED_SHULKER_BOX.orange
    public val MAGENTA_SHULKER_BOX: Block = Blocks.DYED_SHULKER_BOX.magenta
    public val LIGHT_BLUE_SHULKER_BOX: Block = Blocks.DYED_SHULKER_BOX.lightBlue
    public val YELLOW_SHULKER_BOX: Block = Blocks.DYED_SHULKER_BOX.yellow
    public val LIME_SHULKER_BOX: Block = Blocks.DYED_SHULKER_BOX.lime
    public val PINK_SHULKER_BOX: Block = Blocks.DYED_SHULKER_BOX.pink
    public val GRAY_SHULKER_BOX: Block = Blocks.DYED_SHULKER_BOX.gray
    public val LIGHT_GRAY_SHULKER_BOX: Block = Blocks.DYED_SHULKER_BOX.lightGray
    public val CYAN_SHULKER_BOX: Block = Blocks.DYED_SHULKER_BOX.cyan
    public val PURPLE_SHULKER_BOX: Block = Blocks.DYED_SHULKER_BOX.purple
    public val BLUE_SHULKER_BOX: Block = Blocks.DYED_SHULKER_BOX.blue
    public val BROWN_SHULKER_BOX: Block = Blocks.DYED_SHULKER_BOX.brown
    public val GREEN_SHULKER_BOX: Block = Blocks.DYED_SHULKER_BOX.green
    public val RED_SHULKER_BOX: Block = Blocks.DYED_SHULKER_BOX.red
    public val BLACK_SHULKER_BOX: Block = Blocks.DYED_SHULKER_BOX.black
    //? } else {
    /*val WHITE_WOOL: Block = Blocks.WHITE_WOOL
    val ORANGE_WOOL: Block = Blocks.ORANGE_WOOL
    val MAGENTA_WOOL: Block = Blocks.MAGENTA_WOOL
    val LIGHT_BLUE_WOOL: Block = Blocks.LIGHT_BLUE_WOOL
    val YELLOW_WOOL: Block = Blocks.YELLOW_WOOL
    val LIME_WOOL: Block = Blocks.LIME_WOOL
    val PINK_WOOL: Block = Blocks.PINK_WOOL
    val GRAY_WOOL: Block = Blocks.GRAY_WOOL
    val LIGHT_GRAY_WOOL: Block = Blocks.LIGHT_GRAY_WOOL
    val CYAN_WOOL: Block = Blocks.CYAN_WOOL
    val PURPLE_WOOL: Block = Blocks.PURPLE_WOOL
    val BLUE_WOOL: Block = Blocks.BLUE_WOOL
    val BROWN_WOOL: Block = Blocks.BROWN_WOOL
    val GREEN_WOOL: Block = Blocks.GREEN_WOOL
    val RED_WOOL: Block = Blocks.RED_WOOL
    val BLACK_WOOL: Block = Blocks.BLACK_WOOL

    val WHITE_STAINED_GLASS: Block = Blocks.WHITE_STAINED_GLASS
    val ORANGE_STAINED_GLASS: Block = Blocks.ORANGE_STAINED_GLASS
    val MAGENTA_STAINED_GLASS: Block = Blocks.MAGENTA_STAINED_GLASS
    val LIGHT_BLUE_STAINED_GLASS: Block = Blocks.LIGHT_BLUE_STAINED_GLASS
    val YELLOW_STAINED_GLASS: Block = Blocks.YELLOW_STAINED_GLASS
    val LIME_STAINED_GLASS: Block = Blocks.LIME_STAINED_GLASS
    val PINK_STAINED_GLASS: Block = Blocks.PINK_STAINED_GLASS
    val GRAY_STAINED_GLASS: Block = Blocks.GRAY_STAINED_GLASS
    val LIGHT_GRAY_STAINED_GLASS: Block = Blocks.LIGHT_GRAY_STAINED_GLASS
    val CYAN_STAINED_GLASS: Block = Blocks.CYAN_STAINED_GLASS
    val PURPLE_STAINED_GLASS: Block = Blocks.PURPLE_STAINED_GLASS
    val BLUE_STAINED_GLASS: Block = Blocks.BLUE_STAINED_GLASS
    val BROWN_STAINED_GLASS: Block = Blocks.BROWN_STAINED_GLASS
    val GREEN_STAINED_GLASS: Block = Blocks.GREEN_STAINED_GLASS
    val RED_STAINED_GLASS: Block = Blocks.RED_STAINED_GLASS
    val BLACK_STAINED_GLASS: Block = Blocks.BLACK_STAINED_GLASS

    val WHITE_TERRACOTTA: Block = Blocks.WHITE_TERRACOTTA
    val ORANGE_TERRACOTTA: Block = Blocks.ORANGE_TERRACOTTA
    val MAGENTA_TERRACOTTA: Block = Blocks.MAGENTA_TERRACOTTA
    val LIGHT_BLUE_TERRACOTTA: Block = Blocks.LIGHT_BLUE_TERRACOTTA
    val YELLOW_TERRACOTTA: Block = Blocks.YELLOW_TERRACOTTA
    val LIME_TERRACOTTA: Block = Blocks.LIME_TERRACOTTA
    val PINK_TERRACOTTA: Block = Blocks.PINK_TERRACOTTA
    val GRAY_TERRACOTTA: Block = Blocks.GRAY_TERRACOTTA
    val LIGHT_GRAY_TERRACOTTA: Block = Blocks.LIGHT_GRAY_TERRACOTTA
    val CYAN_TERRACOTTA: Block = Blocks.CYAN_TERRACOTTA
    val PURPLE_TERRACOTTA: Block = Blocks.PURPLE_TERRACOTTA
    val BLUE_TERRACOTTA: Block = Blocks.BLUE_TERRACOTTA
    val BROWN_TERRACOTTA: Block = Blocks.BROWN_TERRACOTTA
    val GREEN_TERRACOTTA: Block = Blocks.GREEN_TERRACOTTA
    val RED_TERRACOTTA: Block = Blocks.RED_TERRACOTTA
    val BLACK_TERRACOTTA: Block = Blocks.BLACK_TERRACOTTA

    val WHITE_STAINED_GLASS_PANE: Block = Blocks.WHITE_STAINED_GLASS_PANE
    val ORANGE_STAINED_GLASS_PANE: Block = Blocks.ORANGE_STAINED_GLASS_PANE
    val MAGENTA_STAINED_GLASS_PANE: Block = Blocks.MAGENTA_STAINED_GLASS_PANE
    val LIGHT_BLUE_STAINED_GLASS_PANE: Block = Blocks.LIGHT_BLUE_STAINED_GLASS_PANE
    val YELLOW_STAINED_GLASS_PANE: Block = Blocks.YELLOW_STAINED_GLASS_PANE
    val LIME_STAINED_GLASS_PANE: Block = Blocks.LIME_STAINED_GLASS_PANE
    val PINK_STAINED_GLASS_PANE: Block = Blocks.PINK_STAINED_GLASS_PANE
    val GRAY_STAINED_GLASS_PANE: Block = Blocks.GRAY_STAINED_GLASS_PANE
    val LIGHT_GRAY_STAINED_GLASS_PANE: Block = Blocks.LIGHT_GRAY_STAINED_GLASS_PANE
    val CYAN_STAINED_GLASS_PANE: Block = Blocks.CYAN_STAINED_GLASS_PANE
    val PURPLE_STAINED_GLASS_PANE: Block = Blocks.PURPLE_STAINED_GLASS_PANE
    val BLUE_STAINED_GLASS_PANE: Block = Blocks.BLUE_STAINED_GLASS_PANE
    val BROWN_STAINED_GLASS_PANE: Block = Blocks.BROWN_STAINED_GLASS_PANE
    val GREEN_STAINED_GLASS_PANE: Block = Blocks.GREEN_STAINED_GLASS_PANE
    val RED_STAINED_GLASS_PANE: Block = Blocks.RED_STAINED_GLASS_PANE
    val BLACK_STAINED_GLASS_PANE: Block = Blocks.BLACK_STAINED_GLASS_PANE

    val WHITE_CARPET: Block = Blocks.WHITE_CARPET
    val ORANGE_CARPET: Block = Blocks.ORANGE_CARPET
    val MAGENTA_CARPET: Block = Blocks.MAGENTA_CARPET
    val LIGHT_BLUE_CARPET: Block = Blocks.LIGHT_BLUE_CARPET
    val YELLOW_CARPET: Block = Blocks.YELLOW_CARPET
    val LIME_CARPET: Block = Blocks.LIME_CARPET
    val PINK_CARPET: Block = Blocks.PINK_CARPET
    val GRAY_CARPET: Block = Blocks.GRAY_CARPET
    val LIGHT_GRAY_CARPET: Block = Blocks.LIGHT_GRAY_CARPET
    val CYAN_CARPET: Block = Blocks.CYAN_CARPET
    val PURPLE_CARPET: Block = Blocks.PURPLE_CARPET
    val BLUE_CARPET: Block = Blocks.BLUE_CARPET
    val BROWN_CARPET: Block = Blocks.BROWN_CARPET
    val GREEN_CARPET: Block = Blocks.GREEN_CARPET
    val RED_CARPET: Block = Blocks.RED_CARPET
    val BLACK_CARPET: Block = Blocks.BLACK_CARPET

    val WHITE_BED: Block = Blocks.WHITE_BED
    val ORANGE_BED: Block = Blocks.ORANGE_BED
    val MAGENTA_BED: Block = Blocks.MAGENTA_BED
    val LIGHT_BLUE_BED: Block = Blocks.LIGHT_BLUE_BED
    val YELLOW_BED: Block = Blocks.YELLOW_BED
    val LIME_BED: Block = Blocks.LIME_BED
    val PINK_BED: Block = Blocks.PINK_BED
    val GRAY_BED: Block = Blocks.GRAY_BED
    val LIGHT_GRAY_BED: Block = Blocks.LIGHT_GRAY_BED
    val CYAN_BED: Block = Blocks.CYAN_BED
    val PURPLE_BED: Block = Blocks.PURPLE_BED
    val BLUE_BED: Block = Blocks.BLUE_BED
    val BROWN_BED: Block = Blocks.BROWN_BED
    val GREEN_BED: Block = Blocks.GREEN_BED
    val RED_BED: Block = Blocks.RED_BED
    val BLACK_BED: Block = Blocks.BLACK_BED

    val WHITE_BANNER: Block = Blocks.WHITE_BANNER
    val ORANGE_BANNER: Block = Blocks.ORANGE_BANNER
    val MAGENTA_BANNER: Block = Blocks.MAGENTA_BANNER
    val LIGHT_BLUE_BANNER: Block = Blocks.LIGHT_BLUE_BANNER
    val YELLOW_BANNER: Block = Blocks.YELLOW_BANNER
    val LIME_BANNER: Block = Blocks.LIME_BANNER
    val PINK_BANNER: Block = Blocks.PINK_BANNER
    val GRAY_BANNER: Block = Blocks.GRAY_BANNER
    val LIGHT_GRAY_BANNER: Block = Blocks.LIGHT_GRAY_BANNER
    val CYAN_BANNER: Block = Blocks.CYAN_BANNER
    val PURPLE_BANNER: Block = Blocks.PURPLE_BANNER
    val BLUE_BANNER: Block = Blocks.BLUE_BANNER
    val BROWN_BANNER: Block = Blocks.BROWN_BANNER
    val GREEN_BANNER: Block = Blocks.GREEN_BANNER
    val RED_BANNER: Block = Blocks.RED_BANNER
    val BLACK_BANNER: Block = Blocks.BLACK_BANNER

    val WHITE_SHULKER_BOX: Block = Blocks.WHITE_SHULKER_BOX
    val ORANGE_SHULKER_BOX: Block = Blocks.ORANGE_SHULKER_BOX
    val MAGENTA_SHULKER_BOX: Block = Blocks.MAGENTA_SHULKER_BOX
    val LIGHT_BLUE_SHULKER_BOX: Block = Blocks.LIGHT_BLUE_SHULKER_BOX
    val YELLOW_SHULKER_BOX: Block = Blocks.YELLOW_SHULKER_BOX
    val LIME_SHULKER_BOX: Block = Blocks.LIME_SHULKER_BOX
    val PINK_SHULKER_BOX: Block = Blocks.PINK_SHULKER_BOX
    val GRAY_SHULKER_BOX: Block = Blocks.GRAY_SHULKER_BOX
    val LIGHT_GRAY_SHULKER_BOX: Block = Blocks.LIGHT_GRAY_SHULKER_BOX
    val CYAN_SHULKER_BOX: Block = Blocks.CYAN_SHULKER_BOX
    val PURPLE_SHULKER_BOX: Block = Blocks.PURPLE_SHULKER_BOX
    val BLUE_SHULKER_BOX: Block = Blocks.BLUE_SHULKER_BOX
    val BROWN_SHULKER_BOX: Block = Blocks.BROWN_SHULKER_BOX
    val GREEN_SHULKER_BOX: Block = Blocks.GREEN_SHULKER_BOX
    val RED_SHULKER_BOX: Block = Blocks.RED_SHULKER_BOX
    val BLACK_SHULKER_BOX: Block = Blocks.BLACK_SHULKER_BOX
    *///? }
}
