name: API Baseline Updater

on:
    push:
        branches: [ "4.0" ]

permissions:
    contents: write
    pull-requests: write

jobs:
    baseline-updater:

        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v5
                with:
                    token: ${{ secrets.BOT_TOKEN }}

            -   name: Setup JDK 21
                uses: actions/setup-java@v5
                with:
                    distribution: temurin
                    java-version: '21'

            -   name: Setup gradle
                uses: gradle/actions/setup-gradle@v5

            -   run: chmod +x gradlew
            -   name: Build
                run: ./gradlew build

            -   name: Build with Gradle
                run: ./gradlew updateLegacyAbi || true

            -   name: Check for breaking changes
                env:
                    GH_TOKEN: ${{ secrets.BOT_TOKEN }}
                run: |
                    if ! $(git diff --exit-code versions/26.1/api/26.1.api) || ! $(git diff --exit-code versions/1.21.10/api/1.21.10.api) || ! $(git diff --exit-code versions/1.21.11/api/1.21.11.api);
                    then
                        git config --global user.email "meowtomation@users.noreply.github.com"
                        git config --global user.name "meowtomation"
                        git add .
                        git commit -m "update api dump"
                        git push
                    fi
